apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-baseline-vs-canary
  labels:
    g: m
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-baseline-vs-canary
  template:
    metadata:
      labels:
        app: rollout-baseline-vs-canary
        acs.amadeus.com/securityZone: tnz
        app.kubernetes.io/managed-by: cds
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/version: "1.23"
    spec:
      containers:
      - name: rollout-baseline-vs-canary
        image: argoproj/rollouts-demo:yellow
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      tolerations:
      - key: reservedFor
        operator: Equal
        value: argocd-32
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/argocd-32: 'true'
  strategy:
    canary:
      steps:
      - setWeight: 50
      - experiment:
          templates:
          - name: baseline
            specRef: stable
            template:
              metadata:
                labels:
                  env: x
            metadata:
              labels:
                app: rollout-stable
                x: y
          - name: canary
            specRef: canary
            template:
              metadata:
                labels:
                  env: z
            metadata:
              labels:
                app: rollout-canary
                m: n

