apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  labels:
    acs.amadeus.com/securityZone: anz
    app.kubernetes.io/managed-by: cds
spec:
  replicas: 4
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
        acs.amadeus.com/securityZone: anz
        app.kubernetes.io/managed-by: cds    
    spec:
      containers:
      - name: canary-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - pause: {duration: 10}
      - setWeight: 75
      - pause: {duration: 10}
