apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    acs.amadeus.com/securityZone: anz
    app.kubernetes.io/instance: demo-rollout
    app.kubernetes.io/managed-by: cds
    app.kubernetes.io/name: demo-app
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
